// Auto-generated from stage-ladders.json — DO NOT EDIT manually.
// Edit stage-ladders.json and regenerate this file.
export const STAGE_LADDERS = {
  FORMAT_LADDERS: {
    "film":               ["idea","concept_brief","market_sheet","treatment","story_outline","character_bible","beat_sheet","feature_script","production_draft","deck"],
    "feature":            ["idea","concept_brief","market_sheet","treatment","story_outline","character_bible","beat_sheet","feature_script","production_draft","deck"],
    "tv-series":          ["idea","concept_brief","market_sheet","treatment","story_outline","character_bible","beat_sheet","episode_script","season_master_script","production_draft"],
    "limited-series":     ["idea","concept_brief","market_sheet","treatment","story_outline","character_bible","beat_sheet","episode_script","season_master_script","production_draft"],
    "digital-series":     ["idea","concept_brief","market_sheet","treatment","story_outline","character_bible","beat_sheet","episode_script","season_master_script","production_draft"],
    "vertical-drama":     ["idea","concept_brief","vertical_market_sheet","format_rules","character_bible","season_arc","episode_grid","vertical_episode_beats","episode_script","season_master_script"],
    "documentary":        ["idea","concept_brief","market_sheet","documentary_outline","deck"],
    "documentary-series": ["idea","concept_brief","market_sheet","documentary_outline","deck"],
    "hybrid-documentary": ["idea","concept_brief","market_sheet","documentary_outline","treatment","deck"],
    "short":              ["idea","concept_brief","feature_script"],
    "animation":          ["idea","concept_brief","market_sheet","treatment","character_bible","beat_sheet","feature_script"],
    "anim-series":        ["idea","concept_brief","market_sheet","treatment","story_outline","character_bible","beat_sheet","episode_script","season_master_script","production_draft"],
    "reality":            ["idea","concept_brief","market_sheet","treatment","beat_sheet","episode_script"],
  } as Record<string, string[]>,
  DOC_TYPE_ALIASES: {
    "logline":               "idea",
    "one_pager":             "concept_brief",
    "blueprint":             "treatment",
    "series_bible":          "treatment",
    "treatment":             "treatment",
    "season_outline":        "treatment",
    "outline":               "treatment",
    "architecture":          "story_outline",
    "plot_architecture":     "story_outline",
    "episode_beat_sheet":    "beat_sheet",
    "script":                "feature_script",
    "feature_script":        "feature_script",
    "pilot_script":          "episode_script",
    "episode_script":        "episode_script",
    "episode_1_script":      "episode_script",
    "writers_room":          "series_writer",
    "notes":                 "concept_brief",
    "draft":                 "feature_script",
    "coverage":              "production_draft",
    "complete_season_script": "season_master_script",
  } as Record<string, string>,
  FORMAT_SCRIPT_TYPES: {
    "film":               "feature_script",
    "feature":            "feature_script",
    "short":              "feature_script",
    "animation":          "feature_script",
    "tv-series":          "episode_script",
    "limited-series":     "episode_script",
    "digital-series":     "episode_script",
    "vertical-drama":     "episode_script",
    "anim-series":        "episode_script",
    "reality":            "episode_script",
    "documentary":        "feature_script",
    "documentary-series": "feature_script",
    "hybrid-documentary": "feature_script",
  } as Record<string, string>,
};
