import type { WritingVoicePreset } from './types';

export const WRITING_VOICE_PRESETS: WritingVoicePreset[] = [
  // ═══════════════════════════════════════════════════════════
  // VERTICAL (lane_group = 'vertical')
  // ═══════════════════════════════════════════════════════════
  {
    id: 'high_heat_addictive_vertical',
    label: 'High-Heat Addictive',
    lane_group: 'vertical',
    summary: 'Rapid-fire cliffhangers, punchy dialogue, maximum scroll-lock energy.',
    knobs: { prose_density: 2, dialogue_register: 8, subtext: 3, hook_intensity: 10, emotional_restraint: 2, visuality: 6 },
    constraints: { sentence_len_band: [5, 12], dialogue_ratio_band: [0.55, 0.75], hook_frequency: 'every_beat' },
    do: ['End every scene on a micro-cliffhanger', 'Use short staccato sentences for action', 'Front-load conflict in the first line', 'Keep dialogue punchy — max 2 sentences per turn', 'Use visual verbs over interior monologue'],
    dont: ['Never write description blocks longer than 3 lines', 'Avoid philosophical monologues', 'Never delay the hook past the first beat', 'Don\'t use passive voice in action lines', 'Avoid slow-burn reveals — payoff fast'],
  },
  {
    id: 'tender_kdrama_vertical',
    label: 'Tender K-Drama Romance',
    lane_group: 'vertical',
    summary: 'Emotionally layered romance with longing glances and restrained dialogue.',
    knobs: { prose_density: 5, dialogue_register: 5, subtext: 8, hook_intensity: 6, emotional_restraint: 7, visuality: 8 },
    constraints: { sentence_len_band: [8, 18], dialogue_ratio_band: [0.40, 0.55], hook_frequency: 'every_2_beats' },
    do: ['Describe micro-gestures that reveal emotion', 'Use environment as emotional mirror', 'Build tension through what\'s NOT said', 'Layer scenes with dual meaning', 'End episodes on emotional ache, not action'],
    dont: ['Don\'t have characters state feelings directly', 'Avoid rapid-cut action sequences', 'Never rush the first touch/kiss', 'Don\'t overuse internal monologue', 'Avoid cynical or ironic tone'],
  },
  {
    id: 'comedic_flirty_vertical',
    label: 'Comedic & Flirty',
    lane_group: 'vertical',
    summary: 'Light, witty banter with situational comedy and rom-com energy.',
    knobs: { prose_density: 3, dialogue_register: 9, subtext: 4, hook_intensity: 7, emotional_restraint: 3, visuality: 5 },
    constraints: { sentence_len_band: [5, 14], dialogue_ratio_band: [0.60, 0.80], hook_frequency: 'every_beat' },
    do: ['Lead with banter in every encounter scene', 'Use comedic misunderstandings as structure', 'Give each character a distinct verbal tic', 'Build chemistry through disagreement', 'End scenes on a laugh or a flush'],
    dont: ['Don\'t write flat exposition dialogue', 'Avoid melodramatic crying scenes', 'Never make jokes mean-spirited', 'Don\'t over-describe settings', 'Avoid long monologues'],
  },
  {
    id: 'mystery_hook_machine_vertical',
    label: 'Mystery Hook Machine',
    lane_group: 'vertical',
    summary: 'Relentless mystery pacing — every episode adds a question and half-answers another.',
    knobs: { prose_density: 4, dialogue_register: 6, subtext: 7, hook_intensity: 10, emotional_restraint: 5, visuality: 7 },
    constraints: { sentence_len_band: [6, 15], dialogue_ratio_band: [0.40, 0.60], hook_frequency: 'every_beat' },
    do: ['Plant a new question in every scene', 'Use unreliable narration or perspective shifts', 'End episodes on unanswered reveals', 'Layer clues in environment details', 'Keep suspect behavior ambiguous'],
    dont: ['Never resolve more than half the questions per episode', 'Avoid info-dump exposition', 'Don\'t reveal the culprit before the final act', 'Avoid scenes without tension', 'Never break POV rules established early'],
  },
  {
    id: 'dark_obsession_vertical',
    label: 'Dark Obsession',
    lane_group: 'vertical',
    summary: 'Intense psychological tension, morally grey leads, obsessive relationships.',
    knobs: { prose_density: 6, dialogue_register: 5, subtext: 9, hook_intensity: 8, emotional_restraint: 4, visuality: 8 },
    constraints: { sentence_len_band: [7, 18], dialogue_ratio_band: [0.35, 0.55], hook_frequency: 'every_beat' },
    do: ['Use close POV to create claustrophobic intimacy', 'Write dialogue that means the opposite of what\'s said', 'Describe physical sensation to convey inner state', 'Escalate stakes through small betrayals', 'Make the audience complicit in the protagonist\'s choices'],
    dont: ['Don\'t moralize about character behavior', 'Avoid clear hero/villain binaries', 'Never break tension with comedy relief', 'Don\'t over-explain motivations', 'Avoid happy resolutions without cost'],
  },

  // ═══════════════════════════════════════════════════════════
  // SERIES (lane_group = 'series')
  // ═══════════════════════════════════════════════════════════
  {
    id: 'prestige_intimate_series',
    label: 'Prestige Intimate',
    lane_group: 'series',
    summary: 'Character-driven prestige drama — measured pace, literary dialogue, thematic depth.',
    knobs: { prose_density: 8, dialogue_register: 6, subtext: 9, hook_intensity: 4, emotional_restraint: 8, visuality: 7 },
    constraints: { sentence_len_band: [12, 25], dialogue_ratio_band: [0.35, 0.50], hook_frequency: 'act_outs' },
    do: ['Use silence and pauses as dramatic tools', 'Write dialogue that reveals character through subtext', 'Anchor every scene in a specific sensory detail', 'Build episodes around a single thematic question', 'Let scenes breathe — trust the audience'],
    dont: ['Don\'t use exposition dialogue', 'Avoid plot-driven scene transitions', 'Never sacrifice character for twist', 'Don\'t rush emotional beats', 'Avoid on-the-nose thematic statements'],
  },
  {
    id: 'propulsive_commercial_series',
    label: 'Propulsive Commercial',
    lane_group: 'series',
    summary: 'High-octane broadcast drama — clear stakes, episode-end hooks, broad appeal.',
    knobs: { prose_density: 4, dialogue_register: 7, subtext: 4, hook_intensity: 9, emotional_restraint: 3, visuality: 6 },
    constraints: { sentence_len_band: [7, 16], dialogue_ratio_band: [0.50, 0.65], hook_frequency: 'every_beat' },
    do: ['Open every episode with a cold open hook', 'Use A/B/C storylines per episode', 'End acts on cliffhangers or reveals', 'Keep dialogue snappy and quotable', 'Escalate the central mystery each episode'],
    dont: ['Don\'t let any scene run without conflict', 'Avoid internal monologue over action', 'Never go two acts without a reversal', 'Don\'t make the audience wait for payoff', 'Avoid ambiguous endings'],
  },
  {
    id: 'darkly_comic_series',
    label: 'Darkly Comic',
    lane_group: 'series',
    summary: 'Tonal tightrope between absurd comedy and genuine darkness.',
    knobs: { prose_density: 5, dialogue_register: 8, subtext: 7, hook_intensity: 6, emotional_restraint: 5, visuality: 5 },
    constraints: { sentence_len_band: [8, 18], dialogue_ratio_band: [0.50, 0.65], hook_frequency: 'every_2_beats' },
    do: ['Juxtapose humor with genuine stakes', 'Write characters who are funny because they\'re broken', 'Use deadpan delivery for darkest moments', 'Let comedy emerge from character, not situation', 'Undercut sentimentality with a sharp line'],
    dont: ['Don\'t signal jokes with setup-punchline structure', 'Avoid slapstick or physical comedy', 'Never make violence cartoonish', 'Don\'t break tone for cheap laughs', 'Avoid wholesome resolution without irony'],
  },
  {
    id: 'procedural_crisp_series',
    label: 'Procedural Crisp',
    lane_group: 'series',
    summary: 'Clean case-of-the-week structure with sharp investigative dialogue.',
    knobs: { prose_density: 3, dialogue_register: 7, subtext: 4, hook_intensity: 7, emotional_restraint: 6, visuality: 4 },
    constraints: { sentence_len_band: [6, 14], dialogue_ratio_band: [0.55, 0.70], hook_frequency: 'every_beat' },
    do: ['Open with a case hook in the first 2 pages', 'Use jargon authentically but accessibly', 'Build character through how they work', 'Deliver one surprise per act break', 'Close cases with a thematic echo to the personal story'],
    dont: ['Don\'t let personal drama overwhelm the case', 'Avoid technobabble without context', 'Never have the hero solve it by luck', 'Don\'t repeat case structures across episodes', 'Avoid cold opens longer than 3 pages'],
  },
  {
    id: 'ya_emotional_series',
    label: 'YA Emotional',
    lane_group: 'series',
    summary: 'Emotionally authentic coming-of-age with high relatability and identity themes.',
    knobs: { prose_density: 5, dialogue_register: 7, subtext: 6, hook_intensity: 6, emotional_restraint: 3, visuality: 6 },
    constraints: { sentence_len_band: [8, 16], dialogue_ratio_band: [0.50, 0.65], hook_frequency: 'every_2_beats' },
    do: ['Write dialogue that sounds like real teens — specific, not generic', 'Use music and pop culture references as emotional anchors', 'Build identity crises into every character arc', 'Make friendships as important as romance', 'Show vulnerability as strength'],
    dont: ['Don\'t write teens as mini-adults', 'Avoid after-school-special moralizing', 'Never make adults all-knowing', 'Don\'t resolve trauma in a single episode', 'Avoid stereotypical clique dynamics'],
  },

  // ═══════════════════════════════════════════════════════════
  // FEATURE (lane_group = 'feature')
  // ═══════════════════════════════════════════════════════════
  {
    id: 'cinematic_clean_feature',
    label: 'Cinematic Clean',
    lane_group: 'feature',
    summary: 'Elegant, economical prose — every word earns its place, strong visual writing.',
    knobs: { prose_density: 7, dialogue_register: 5, subtext: 8, hook_intensity: 5, emotional_restraint: 7, visuality: 9 },
    constraints: { sentence_len_band: [10, 22], dialogue_ratio_band: [0.30, 0.45], hook_frequency: 'act_outs' },
    do: ['Write action lines that read like camera direction', 'Use white space on the page as pacing', 'Reveal character through behavior, not speech', 'Open with an image that encapsulates the theme', 'End scenes on a visual, not a line'],
    dont: ['Don\'t write camera directions explicitly', 'Avoid dialogue-heavy scenes over 2 pages', 'Never use adverbs in action lines', 'Don\'t describe what we can\'t see or hear', 'Avoid flashbacks unless structurally essential'],
  },
  {
    id: 'crowdpleaser_highconcept_feature',
    label: 'Crowd-Pleaser High-Concept',
    lane_group: 'feature',
    summary: 'Big idea, clear hook, broad emotional beats — studio four-quadrant energy.',
    knobs: { prose_density: 4, dialogue_register: 7, subtext: 3, hook_intensity: 9, emotional_restraint: 3, visuality: 7 },
    constraints: { sentence_len_band: [7, 16], dialogue_ratio_band: [0.45, 0.60], hook_frequency: 'every_beat' },
    do: ['State the concept in the first 5 pages', 'Build set pieces around the high concept', 'Give the hero a clear want and need', 'Deliver an emotional climax that earns tears or cheers', 'Make the rules of the world clear and consistent'],
    dont: ['Don\'t bury the concept in backstory', 'Avoid ambiguous endings', 'Never let the concept overshadow character', 'Don\'t write scenes that don\'t serve the concept', 'Avoid cynicism — commit to the emotional promise'],
  },
  {
    id: 'elevated_genre_feature',
    label: 'Elevated Genre',
    lane_group: 'feature',
    summary: 'Genre thrills with prestige execution — A24/Neon territory.',
    knobs: { prose_density: 7, dialogue_register: 5, subtext: 8, hook_intensity: 7, emotional_restraint: 6, visuality: 9 },
    constraints: { sentence_len_band: [9, 20], dialogue_ratio_band: [0.30, 0.50], hook_frequency: 'every_2_beats' },
    do: ['Use genre mechanics to explore a real human theme', 'Write dread through atmosphere, not jump scares', 'Subvert one genre expectation per act', 'Ground supernatural/genre elements in emotional reality', 'Make the monster a metaphor'],
    dont: ['Don\'t rely on genre clichés for scares/thrills', 'Avoid exposition about genre rules', 'Never sacrifice character for spectacle', 'Don\'t break the grounded tone for cheap effect', 'Avoid third-act CGI escalation over character'],
  },
  {
    id: 'lyrical_arthouse_feature',
    label: 'Lyrical Arthouse',
    lane_group: 'feature',
    summary: 'Poetic, image-driven storytelling — rhythm over plot, sensation over explanation.',
    knobs: { prose_density: 9, dialogue_register: 3, subtext: 10, hook_intensity: 2, emotional_restraint: 8, visuality: 10 },
    constraints: { sentence_len_band: [14, 30], dialogue_ratio_band: [0.15, 0.30], hook_frequency: 'act_outs' },
    do: ['Write action lines with rhythmic cadence', 'Use repetition as structural motif', 'Describe light, texture, and sound over plot', 'Let meaning emerge from juxtaposition', 'Trust images to carry emotion without dialogue'],
    dont: ['Don\'t explain themes through dialogue', 'Avoid conventional three-act structure', 'Never rush transitions between scenes', 'Don\'t use genre conventions', 'Avoid on-the-nose symbolism'],
  },
  {
    id: 'action_pulse_feature',
    label: 'Action Pulse',
    lane_group: 'feature',
    summary: 'Muscular, kinetic writing — clear geography, visceral action, lean dialogue.',
    knobs: { prose_density: 3, dialogue_register: 6, subtext: 3, hook_intensity: 9, emotional_restraint: 4, visuality: 8 },
    constraints: { sentence_len_band: [5, 13], dialogue_ratio_band: [0.35, 0.50], hook_frequency: 'every_beat' },
    do: ['Write action sequences with clear spatial geography', 'Use short sentences for impact', 'Build character through choices under pressure', 'Escalate physical stakes every 10 pages', 'Make every action sequence serve the story'],
    dont: ['Don\'t write confusing action geography', 'Avoid dialogue during peak action', 'Never stop momentum for exposition', 'Don\'t describe every punch — write rhythm', 'Avoid invincible heroes — show cost'],
  },

  // ═══════════════════════════════════════════════════════════
  // DOCUMENTARY (lane_group = 'documentary')
  // ═══════════════════════════════════════════════════════════
  {
    id: 'investigative_doc',
    label: 'Investigative',
    lane_group: 'documentary',
    summary: 'Evidence-driven narrative with revelatory structure and journalistic rigor.',
    knobs: { prose_density: 5, dialogue_register: 6, subtext: 5, hook_intensity: 8, emotional_restraint: 6, visuality: 5 },
    constraints: { sentence_len_band: [8, 18], dialogue_ratio_band: [0.40, 0.55], hook_frequency: 'every_beat' },
    do: ['Structure around the investigation timeline', 'Use documents and data as dramatic reveals', 'Build tension through what we don\'t know yet', 'Let subjects speak in their own words', 'End episodes with a new question or revelation'],
    dont: ['Don\'t editorialize in narration', 'Avoid leading interview questions in scripted scenes', 'Never reveal conclusions before evidence', 'Don\'t oversimplify complex systems', 'Avoid sensationalism over substance'],
  },
  {
    id: 'human_intimate_doc',
    label: 'Human Intimate',
    lane_group: 'documentary',
    summary: 'Character-centered vérité — empathy over argument, observation over narration.',
    knobs: { prose_density: 6, dialogue_register: 4, subtext: 7, hook_intensity: 4, emotional_restraint: 7, visuality: 8 },
    constraints: { sentence_len_band: [10, 22], dialogue_ratio_band: [0.30, 0.50], hook_frequency: 'act_outs' },
    do: ['Follow the subject\'s daily rhythms', 'Use observational scenes over interviews', 'Build emotional arc through accumulated moments', 'Show environment as character context', 'Trust silence and pauses'],
    dont: ['Don\'t impose narrative structure over lived experience', 'Avoid voice-of-God narration', 'Never exploit vulnerability for drama', 'Don\'t rush to conflict', 'Avoid reductive character summaries'],
  },
  {
    id: 'poetic_observational_doc',
    label: 'Poetic Observational',
    lane_group: 'documentary',
    summary: 'Meditative, image-first documentary — atmosphere and texture over argument.',
    knobs: { prose_density: 8, dialogue_register: 2, subtext: 9, hook_intensity: 2, emotional_restraint: 9, visuality: 10 },
    constraints: { sentence_len_band: [12, 28], dialogue_ratio_band: [0.10, 0.25], hook_frequency: 'act_outs' },
    do: ['Write scene descriptions as visual poetry', 'Use natural sound as narrative element', 'Build meaning through visual juxtaposition', 'Let duration create emotional weight', 'Describe light and season as story markers'],
    dont: ['Don\'t use narration to explain images', 'Avoid conventional interview setups', 'Never impose conflict structure', 'Don\'t use music to manipulate emotion', 'Avoid rapid editing in scene descriptions'],
  },
  {
    id: 'pop_explainer_doc',
    label: 'Pop Explainer',
    lane_group: 'documentary',
    summary: 'Energetic, accessible storytelling — graphics-friendly, clear narrative drive.',
    knobs: { prose_density: 3, dialogue_register: 8, subtext: 3, hook_intensity: 8, emotional_restraint: 3, visuality: 6 },
    constraints: { sentence_len_band: [6, 14], dialogue_ratio_band: [0.45, 0.65], hook_frequency: 'every_beat' },
    do: ['Open with a surprising fact or question', 'Use metaphors to explain complex systems', 'Build episodes around a central question answered', 'Mix expert interviews with real-world examples', 'End with a "so what" that connects to the viewer'],
    dont: ['Don\'t assume prior knowledge', 'Avoid jargon without immediate context', 'Never lecture — always narrate', 'Don\'t let data overwhelm story', 'Avoid segments longer than 5 minutes without a shift'],
  },
];
