export const STAGE_LABELS: Record<string, string> = {
  idea:                   'Idea',
  concept_brief:          'Concept Brief',
  vertical_market_sheet:  'Market Sheet',
  format_rules:           'Format Rules',
  character_bible:        'Character Bible',
  season_arc:             'Season Arc',
  episode_grid:           'Episode Grid',
  vertical_episode_beats: 'Episode Beats',
  season_script:          'Season Script',
  treatment:              'Treatment',
  beat_sheet:             'Beat Sheet',
  market_sheet:           'Market Sheet',
  nec:                    'Narrative Engine',
  project_overview:       'Project Overview',
  market_positioning:     'Market Positioning',
  story_outline:          'Story Outline',
  series_writer:          'Series Writer',
  script:                 'Script',
  feature_script:         'Feature Script',
};
