ALTER TABLE public.auto_run_jobs
  ADD COLUMN IF NOT EXISTS frontier_version_id UUID NULL,
  ADD COLUMN IF NOT EXISTS frontier_ci NUMERIC NULL,
  ADD COLUMN IF NOT EXISTS frontier_gp NUMERIC NULL,
  ADD COLUMN IF NOT EXISTS frontier_attempts INTEGER NOT NULL DEFAULT 0;